/*
 SQL code to populate all fixed categories
*/
INSERT INTO Category (label, tier) VALUES 
  ('Car', 1),
  ('Truck', 1),
  ('Sedan', 2),
  ('Hatchback', 2),
  ('SUV', 2),
  ('Truck', 2),
  ('Toyota RAV-4', 3),
  ('Ford Explorer', 3),
  ('Mazda3 Hatchback', 3),
  ('Toyota Prius', 3),
  ('Green Ford Explorer', 4),
  ('Gray Ford Explorer', 4),
  ('White Ford Explorer', 4),
  ('Brown Ford Explorer', 4),
  ('Black Ford Explorer', 4),
  ('Blue Ford Explorer', 4),
  ('Red Ford Explorer', 4),
  ('Green Toyota RAV-4', 4),
  ('Gray Toyota RAV-4', 4),
  ('White Toyota RAV-4', 4),
  ('Brown Toyota RAV-4', 4),
  ('Black Toyota RAV-4', 4),
  ('Blue Toyota RAV-4', 4),
  ('Red Toyota RAV-4', 4),
  ('Green Mazda3 Hatchback', 4),
  ('Gray Mazda3 Hatchback', 4),
  ('White Mazda3 Hatchback', 4),
  ('Brown Mazda3 Hatchback', 4),
  ('Black Mazda3 Hatchback', 4),
  ('Blue Mazda3 Hatchback', 4),
  ('Red Mazda3 Hatchback', 4),
  ('Green Toyota Prius', 4),
  ('Gray Toyota Prius', 4),
  ('White Toyota Prius', 4),
  ('Brown Toyota Prius', 4),
  ('Black Toyota Prius', 4),
  ('Blue Toyota Prius', 4),
  ('Red Toyota Prius', 4);
