# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 826)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(24)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 841, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 50, 961, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.formLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.step1Label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.step1Label.setFont(font)
        self.step1Label.setObjectName("step1Label")
        self.horizontalLayout.addWidget(self.step1Label)
        self.step1ChooseTierComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.step1ChooseTierComboBox.setFont(font)
        self.step1ChooseTierComboBox.setObjectName("step1ChooseTierComboBox")
        self.step1ChooseTierComboBox.addItem("")
        self.step1ChooseTierComboBox.addItem("")
        self.step1ChooseTierComboBox.addItem("")
        self.step1ChooseTierComboBox.addItem("")
        self.horizontalLayout.addWidget(self.step1ChooseTierComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.step2Label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.step2Label.setFont(font)
        self.step2Label.setObjectName("step2Label")
        self.horizontalLayout.addWidget(self.step2Label)
        self.step2ChooseModelComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.step2ChooseModelComboBox.setFont(font)
        self.step2ChooseModelComboBox.setObjectName("step2ChooseModelComboBox")
        self.step2ChooseModelComboBox.addItem("")
        self.step2ChooseModelComboBox.addItem("")
        self.step2ChooseModelComboBox.addItem("")
        self.step2ChooseModelComboBox.addItem("")
        self.horizontalLayout.addWidget(self.step2ChooseModelComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.step3UploadImageOrVideoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.step3UploadImageOrVideoLabel.setFont(font)
        self.step3UploadImageOrVideoLabel.setObjectName("step3UploadImageOrVideoLabel")
        self.horizontalLayout.addWidget(self.step3UploadImageOrVideoLabel)
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 140, 961, 631))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tiered Objection Detection - Image and Video Detection"))
        self.step1Label.setText(_translate("MainWindow", "Step 1: Choose tier!"))
        self.step1ChooseTierComboBox.setItemText(0, _translate("MainWindow", "Tier 1"))
        self.step1ChooseTierComboBox.setItemText(1, _translate("MainWindow", "Tier 2"))
        self.step1ChooseTierComboBox.setItemText(2, _translate("MainWindow", "Tier 3"))
        self.step1ChooseTierComboBox.setItemText(3, _translate("MainWindow", "Tier 4"))
        self.step2Label.setText(_translate("MainWindow", "Step 2: Choose model!"))
        self.step2ChooseModelComboBox.setItemText(0, _translate("MainWindow", "Faster RCNN Inception V2 Coco"))
        self.step2ChooseModelComboBox.setItemText(1, _translate("MainWindow", "Faster RCNN Resnet101 Kitti"))
        self.step2ChooseModelComboBox.setItemText(2, _translate("MainWindow", "RFCN Resnet101 Coco"))
        self.step2ChooseModelComboBox.setItemText(3, _translate("MainWindow", "Faster RCNN Resnet101 Kitti"))
        self.step3UploadImageOrVideoLabel.setText(_translate("MainWindow", "Step 3: Upload image or video!"))
        self.pushButton_2.setText(_translate("MainWindow", "Upload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
